### PR TITLE
Use percent-decoded url in request

### PR DESCRIPTION
**Pull request by onur**
#43 introduced a new error. Using path directly in request is causing panic if requested path have some spaces. This patch is using parsed URL and adding a test for percent decoded URLs.

### CODE REVIEW

**Comment by Hoverbear** [comment]
Thanks for this! :)

**Comment by onur** [comment]
@Hoverbear maybe we should move this repo to iron organisation, just a suggestion :smile:

**Comment by Hoverbear** [comment]
@onur I agree with you but I can't create new repos in the Iron org.

**Comment by reem** [comment]
I've moved the repo to the iron organization, hopefully this will smooth maintenance.

**Comment by onur** [comment]
@reem thank you very much!

@Hoverbear I hope you can release a new version of iron-test crate.

**Comment by Hoverbear** [comment]
Thanks Reem!

**Pull request merged**
